$here = @'
"""Append model cell (cell index 7) to the notebook."""
import json
from pathlib import Path

NB_PATH = Path(r'c:\Projects\lip_reading\notebooks\Direct_Baseline_Colab.ipynb')
nb = json.loads(NB_PATH.read_text(encoding='utf-8'))
cells = nb['cells']

# Markdown "## 4. The model"
cells.append({'cell_type': 'markdown', 'metadata': {}, 'source': [
    '## 4. The model (GRU + Bahdanau attention)',
    '',
    'Bidirectional GRU encoder reads ARPAbet phoneme tokens; attention-equipped GRU decoder writes English characters. Vocabularies are built from the training set on first call.',
]})

# Code cell: full model + helpers
ml = []
ml.append('import csv, random, re, time')
ml.append('from collections import Counter')
ml.append('from typing import List, Tuple')
ml.append('import numpy as np')
ml.append('import torch.nn as nn')
ml.append('import torch.nn.functional as F')
ml.append('from torch.utils.data import DataLoader, Dataset')
ml.append('')
ml.append('SEED = 0')
ml.append('random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)')
ml.append('')
ml.append('PAD, BOS, EOS, UNK = 0, 1, 2, 3')
ml.append('')
ml.append('def clean_phonemes(raw):')
ml.append('    raw = (raw or \'\').strip()')
ml.append('    raw = re.sub(r\'<SOS>|<EOS>\', \'\', raw)')
ml.append('    raw = re.sub(r\'[012]\', \'\', raw)')
ml.append('    raw = raw.replace(\'<space>\', \' \')')
ml.append('    return re.sub(r\'\\s+\', \' \', raw).strip()')
ml.append('')
ml.append('def clean_text(raw):')
ml.append('    raw = (raw or \'\').lower()')
ml.append('    raw = re.sub(r"[^a-z \']+", \' \', raw)')
ml.append('    return re.sub(r\'\\s+\', \' \', raw).strip()')
ml.append('')
ml.append('phoneme_vocab, text_vocab = {}, {}')
ml.append('phoneme_inv, text_inv = {}, {}')
ml.append('')
ml.append('def build_vocabs(train_pairs):')
ml.append('    global phoneme_vocab, text_vocab, phoneme_inv, text_inv')
ml.append('    phonemes = Counter(p for p, _ in train_pairs for p in p.split())')
ml.append('    texts    = Counter(c for _, t in train_pairs for c in t)')
ml.append('    phoneme_vocab = {\'<PAD>\': PAD, \'<BOS>\': BOS, \'<EOS>\': EOS, \'<UNK>\': UNK}')
ml.append('    for p, _ in phonemes.most_common(PHONEME_VOCAB_MAX - 4):')
ml.append('        phoneme_vocab.setdefault(p, len(phoneme_vocab))')
ml.append('    text_vocab = {\'<PAD>\': PAD, \'<BOS>\': BOS, \'<EOS>\': EOS, \'<UNK>\': UNK, \' \': len(text_vocab)}')
ml.append('    for c, _ in texts.most_common(TEXT_VOCAB_MAX - 5):')
ml.append('        if c == \' \':')
ml.append('            continue')
ml.append('        text_vocab.setdefault(c, len(text_vocab))')
ml.append('    phoneme_inv = {v: k for k, v in phoneme_vocab.items()}')
ml.append('    text_inv    = {v: k for k, v in text_vocab.items()}')
ml.append('    print(f\'  Vocab: phonemes={len(phoneme_vocab)}  text_chars={len(text_vocab)}\')')
ml.append('')
ml.append('def encode_phonemes(s):')
ml.append('    return [phoneme_vocab.get(t, phoneme_vocab[\'<UNK>\']) for t in s.split()]')
ml.append('')
ml.append('def encode_text(s):')
ml.append('    return [text_vocab.get(c, text_vocab[\'<UNK>\']) for c in s]')
ml.append('')
ml.append('class PhonemeTextDataset(Dataset):')
ml.append('    def __init__(self, pairs):')
ml.append('        self.src = [encode_phonemes(p) for p, _ in pairs]')
ml.append('        self.tgt_in, self.tgt_out = [], []')
ml.append('        for _, t in pairs:')
ml.append('            ids = encode_text(t)[: MAX_TEXT_LEN - 2]')
ml.append('            self.tgt_in.append([BOS] + ids)')
ml.append('            self.tgt_out.append(ids + [EOS])')
ml.append('    def __len__(self): return len(self.src)')
ml.append('    def __getitem__(self, i): return self.src[i], self.tgt_in[i], self.tgt_out[i]')
ml.append('')
ml.append('def collate(batch):')
ml.append('    srcs, tgts_in, tgts_out = zip(*batch)')
ml.append('    def pad(seqs, pad_id=PAD):')
ml.append('        m = max(len(s) for s in seqs)')
ml.append('        return torch.tensor([s + [pad_id]*(m-len(s)) for s in seqs], dtype=torch.long)')
ml.append('    src   = pad(srcs)')
ml.append('    tgt_i = pad(tgts_in)')
ml.append('    tgt_o = pad(tgts_out)')
ml.append('    mask  = (src == PAD)')
ml.append('    return src, tgt_i, tgt_o, mask')
ml.append('')
ml.append('class Encoder(nn.Module):')
ml.append('    """Bidirectional GRU encoder. Returns per-token outputs so the')
ml.append('    decoder can attend over every position."""')
ml.append('    def __init__(self, vocab, emb, hid, n_layers, drop):')
ml.append('        super().__init__()')
ml.append('        self.emb = nn.Embedding(vocab, emb, padding_idx=PAD)')
ml.append('        self.rnn = nn.GRU(emb, hid, n_layers,')
ml.append('                          dropout=drop if n_layers > 1 else 0.0,')
ml.append('                          batch_first=True, bidirectional=True)')
ml.append('        self.hid = hid; self.n_layers = n_layers')
ml.append('    def forward(self, src, src_mask):')
ml.append('        emb = self.emb(src)')
ml.append('        out, _ = self.rnn(emb)')
ml.append('        return out')
ml.append('')
ml.append('class BahdanauAttention(nn.Module):')
ml.append('    """Additive attention: e_t = v^T tanh(W_h dec_h + W_e enc_out)."""')
ml.append('    def __init__(self, enc_dim, dec_dim, attn_dim):')
ml.append('        super().__init__()')
ml.append('        self.W_h = nn.Linear(dec_dim, attn_dim, bias=False)')
ml.append('        self.W_e = nn.Linear(enc_dim, attn_dim, bias=False)')
ml.append('        self.v   = nn.Linear(attn_dim, 1, bias=False)')
ml.append('    def forward(self, dec_h, enc_outs, src_mask):')
ml.append('        scores = self.v(torch.tanh(self.W_h(dec_h).unsqueeze(1) + self.W_e(enc_outs))).squeeze(-1)')
ml.append('        scores = scores.masked_fill(src_mask, float(\'-inf\'))')
ml.append('        alpha  = F.softmax(scores, dim=-1)')
ml.append('        ctx    = torch.bmm(alpha.unsqueeze(1), enc_outs).squeeze(1)')
ml.append('        return ctx, alpha')
ml.append('')
ml.append('class AttnDecoder(nn.Module):')
ml.append('    """1-layer GRU decoder with cross-attention to encoder outputs."""')
ml.append('    def __init__(self, vocab, emb, dec_hid, enc_dim, n_layers, drop):')
ml.append('        super().__init__()')
ml.append('        self.emb  = nn.Embedding(vocab, emb, padding_idx=PAD)')
ml.append('        self.attn = BahdanauAttention(enc_dim, dec_hid, attn_dim=dec_hid)')
ml.append('        self.rnn  = nn.GRU(emb + enc_dim, dec_hid, n_layers,')
ml.append('                           dropout=drop if n_layers > 1 else 0.0,')
ml.append('                           batch_first=True)')
ml.append('        self.fc   = nn.Linear(dec_hid + enc_dim + emb, vocab)')
ml.append('        self.dec_hid = dec_hid; self.n_layers = n_layers')
ml.append('    def forward(self, tgt_in, dec_h0, enc_outs, src_mask):')
ml.append('        B, Td = tgt_in.shape')
ml.append('        emb = self.emb(tgt_in)')
ml.append('        outputs = []')
ml.append('        h = dec_h0.unsqueeze(0)')
ml.append('        for t in range(Td):')
ml.append('            ctx, _ = self.attn(h.squeeze(0), enc_outs, src_mask)')
ml.append('            rnn_in = torch.cat([emb[:, t, :], ctx], dim=-1).unsqueeze(1)')
ml.append('            out, h = self.rnn(rnn_in, h)')
ml.append('            out_t  = self.fc(torch.cat([out.squeeze(1), ctx, emb[:, t, :]], dim=-1))')
ml.append('            outputs.append(out_t)')
ml.append('        return torch.stack(outputs, dim=1)')
ml.append('')
ml.append('class Seq2Seq(nn.Module):')
ml.append('    def __init__(self, src_v, tgt_v):')
ml.append('        super().__init__()')
ml.append('        self.enc = Encoder(src_v, EMB_DIM, HID_DIM, N_LAYERS, DROPOUT)')
ml.append('        self.bridge = nn.Linear(2 * HID_DIM, HID_DIM)')
ml.append('        self.dec    = AttnDecoder(tgt_v, EMB_DIM, HID_DIM,')
ml.append('                                  enc_dim=2 * HID_DIM,')
ml.append('                                  n_layers=N_LAYERS, drop=DROPOUT)')
ml.append('    def forward(self, src, src_mask, tgt_in):')
ml.append('        enc_outs = self.enc(src, src_mask)')
ml.append('        ctx_init = enc_outs.mean(dim=1)')
ml.append('        dec_h0   = self.bridge(ctx_init)')
ml.append('        return self.dec(tgt_in, dec_h0, enc_outs, src_mask)')
ml.append('')
ml.append('@torch.no_grad()')
ml.append('def greedy_decode(model, src, max_len=MAX_TEXT_LEN):')
ml.append('    model.eval()')
ml.append('    src = src.unsqueeze(0).to(DEVICE)')
ml.append('    mask = (src == PAD)')
ml.append('    enc_outs = model.enc(src, mask)')
ml.append('    ctx_init = enc_outs.mean(dim=1)')
ml.append('    dec_h0   = model.bridge(ctx_init)')
ml.append('    y = torch.tensor([[BOS]], device=DEVICE)')
ml.append('    out_ids = []')
ml.append('    for _ in range(max_len):')
ml.append('        logits = model.dec(y, dec_h0, enc_outs, mask)[:, -1, :]')
ml.append('        nxt = int(logits.argmax(-1).item())')
ml.append('        if nxt == EOS:')
ml.append('            break')
ml.append('        out_ids.append(nxt)')
ml.append('        y = torch.cat([y, torch.tensor([[nxt]], device=DEVICE)], dim=1)')
ml.append('    return out_ids')
ml.append('')
ml.append('def detok(ids):')
ml.append('    return \'\'.join(text_inv.get(i, \'?\') for i in ids)')
ml.append('')
ml.append('def edit_distance(a, b):')
ml.append('    n, m = len(a), len(b)')
ml.append('    dp = [[0]*(m+1) for _ in range(n+1)]')
ml.append('    for i in range(n+1): dp[i][0] = i')
ml.append('    for j in range(m+1): dp[0][j] = j')
ml.append('    for i in range(1, n+1):')
ml.append('        for j in range(1, m+1):')
ml.append('            cost = 0 if a[i-1] == b[j-1] else 1')
ml.append('            dp[i][j] = min(dp[i-1][j]+1, dp[i][j-1]+1, dp[i-1][j-1]+cost)')
ml.append('    return dp[n][m], n')

cells.append({'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': ml})

NB_PATH.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print('model cell appended, total cells =', len(cells))
'@

Set-Content -Path c:\Projects\lip_reading\rebuild_nb.py -Value $here -Encoding UTF8 -NoNewline
python c:\Projects\lip_reading\rebuild_nb.py