"""Recover the editable chapter markdown from dissertation_draft_v16.docx after the
source .md files were lost. Reconstructs headings, paragraphs, pipe tables, and the
figure references (mapped by their known order of appearance). Writes chapter_1.md
through chapter_12.md and references.md; the preliminaries are regenerated by
build_dissertation.py and are skipped here.
"""

import os
from docx import Document
from docx.table import Table
from docx.text.paragraph import Paragraph
from docx.oxml.ns import qn

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "dissertation.docx")

# Figures in order of appearance in the document.
FIGS = ["figures/gantt.png", "figures/methodology.png", "figures/eda_lengths.png",
        "figures/eda_duplication.png", "figures/robustness.png", "figures/confusion_clean.png"]

doc = Document(SRC)


def para_has_image(p):
    return bool(p._p.findall(".//" + qn("w:drawing")))


def table_to_md(t):
    rows = [[c.text.strip().replace("\n", " ") for c in r.cells] for r in t.rows]
    if not rows:
        return []
    out = ["| " + " | ".join(rows[0]) + " |",
           "| " + " | ".join("---" for _ in rows[0]) + " |"]
    for r in rows[1:]:
        out.append("| " + " | ".join(r) + " |")
    return out


# Walk body; start a new file at each chapter/References H1.
current = None          # list of markdown lines for the current file
current_name = None
files = {}
fig_i = 0
pending_caption_for_fig = None
children = list(doc.element.body.iterchildren())

i = 0
while i < len(children):
    child = children[i]
    if child.tag == qn("w:p"):
        p = Paragraph(child, doc)
        style = p.style.name or ""
        text = p.text.strip()

        if style == "Heading 1":
            if text.startswith("Chapter ") or text == "References":
                # start a new output file
                if text == "References":
                    current_name = "references.md"
                else:
                    num = text.split(".")[0].replace("Chapter ", "").strip()
                    current_name = f"chapter_{num}.md"
                current = []
                files[current_name] = current
                current.append(f"# {text}")
                current.append("")
            else:
                current = None  # preliminary section, skip
            i += 1
            continue

        if current is None:
            i += 1
            continue

        if style == "Heading 2":
            current.append(f"## {text}"); current.append(""); i += 1; continue
        if style == "Heading 3":
            current.append(f"### {text}"); current.append(""); i += 1; continue

        if para_has_image(p):
            # caption is the next paragraph (italic, centered)
            cap = ""
            if i + 1 < len(children) and children[i+1].tag == qn("w:p"):
                cap = Paragraph(children[i+1], doc).text.strip()
            fig = FIGS[fig_i] if fig_i < len(FIGS) else "figures/MISSING.png"
            fig_i += 1
            current.append(f"![{cap}]({fig})"); current.append("")
            i += 2  # skip caption paragraph
            continue

        if text:
            current.append(text); current.append("")
        i += 1

    elif child.tag == qn("w:tbl"):
        if current is not None:
            current.extend(table_to_md(Table(child, doc)))
            current.append("")
        i += 1
    else:
        i += 1

for name, lines in files.items():
    with open(os.path.join(HERE, name), "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    print(f"wrote {name}  ({len(' '.join(lines).split())} words)")

print(f"\nrecovered {len(files)} files, {fig_i} figure references")
